# -*- coding: utf-8 -*-
"""project2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1keWzMlTCQz7ctPyeyogzUzVsVpz4UwEE
"""

import pandas as pd
import numpy as np

# Load CSV files
train = pd.read_csv("/content/train.csv")
test = pd.read_csv("/content/test.csv")
gender = pd.read_csv("/content/gender_submission.csv")

# Fill missing Age values
train["Age"] = train["Age"].fillna(train["Age"].mean())

# Basic Analysis from train dataset
print("Total Passengers (Train):", len(train))

# Survival Percentage
survival_percent = np.mean(train["Survived"]) * 100
print("Survival Percentage:", survival_percent)

# Survival by Gender
print("\nSurvival Rate by Gender:")
print(train.groupby("Sex")["Survived"].mean())

# Highest & Lowest Fare
print("\nHighest Fare:", np.max(train["Fare"]))
print("Lowest Fare:", np.min(train["Fare"]))